# Generated by Django 4.2 on 2025-02-12 19:14

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_message_body_alter_room_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=150, validators=[django.core.validators.MinLengthValidator(3, 'Please provide a name.')]),
        ),
        migrations.AlterField(
            model_name='room',
            name='topic',
            field=models.ForeignKey(max_length=150, on_delete=django.db.models.deletion.PROTECT, to='base.topic', validators=[django.core.validators.MinLengthValidator(3, 'Please provide a topic name.')]),
        ),
    ]
