# Generated by Django 4.2 on 2025-02-12 19:46

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_room_name_alter_room_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='topic',
            field=models.ForeignKey(max_length=150, on_delete=django.db.models.deletion.PROTECT, to='base.topic'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='name',
            field=models.CharField(max_length=150, validators=[django.core.validators.MinLengthValidator(3, 'Please provide a topic name.')]),
        ),
    ]
