# Generated by Django 4.2 on 2025-02-13 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_room_topic_alter_topic_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='replied_msg',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='base.message'),
        ),
    ]
